import * as yup from 'yup';

const form7ValidationSchema = yup.object().shape({
  title: yup.string(),
  initials: yup.string(),
  surname: yup.string(),
  firstname: yup.string(),
  lastname: yup.string(),
  known: yup.string(),
  spouses: yup.string(),
  id: yup.string(),
  pnumber: yup.string(),
  pcountry: yup.string(),
  emergency: yup.string(),
  cell: yup.string(),
  landline: yup.string(),
  ecell: yup.string(),
  ehome: yup.string(),
  ebusiness: yup.string(),
  efax: yup.string(),
  email: yup.string(),
  holdername: yup.string(),
  bankname: yup.string(),
  number: yup.string(),
  branch: yup.string(),
  type: yup.string(),
  runit: yup.string(),
  rcomplex: yup.string(),
  rsnumber: yup.string(),
  rsname: yup.string(),
  rsuburb: yup.string(),
  rcity: yup.string(),
  rpostal: yup.string(),
  wfnumber: yup.string(),
  wcomplex: yup.string(),
  wsnumber: yup.string(),
  wsname: yup.string(),
  wsuburb: yup.string(),
  wcity: yup.string(),
  wpostal: yup.string(),
  ppnumber: yup.string(),
  ppcity: yup.string(),
  ppcode: yup.string(),
  toffice: yup.string(),
  tnumber: yup.string(),
  directive: yup.string(),
  dnumber: yup.string()
});

export default form7ValidationSchema;